// Generated by CoffeeScript 1.11.1
(function() {
  var AppView, Context, DOM, Post, events;

  Post = require('ppost');

  DOM = require('./core/tree-one');

  AppView = require('./view/app-view');

  events = require('../utils/events');

  Context = (function() {
    function Context() {
      this.startup();
    }

    Context.prototype.startup = function() {
      document.body.style.backgroundColor = '#222222';
      DOM.render(DOM.create(AppView, {}), document.querySelector('.app'), this);
      return null;
    };

    return Context;

  })();

  module.exports = new Context();

}).call(this);

//# sourceMappingURL=context.js.map
