// Generated by CoffeeScript 1.12.5
(function() {
  module.exports = {
    CURSORS_CHANGED: 'cursorsChanged',
    SELECTIONS_CHANGED: 'selectionsChanged',
    TEXT_UPDATED: 'textUpdated',
    INSERT_TEXT: 'insertText',
    ENTER: 'enter',
    BACKSPACE: 'backspace',
    DELETE: 'delete',
    UNDO: 'undo',
    REDO: 'redo',
    COPY: 'copy',
    PASTE: 'paste',
    CUT: 'cut',
    SELECT_ALL: 'selectAll',
    FIND_IN_FILE: 'findInFile',
    REPLACE_IN_FILE: 'replaceInFile',
    DELETE_LINE: 'deleteLine',
    MERGE_LINES: 'mergeLines',
    MOVE_CURSOR_LEFT: 'moveCursorLeft',
    MOVE_CURSOR_RIGHT: 'moveCursorRight',
    MOVE_CURSOR_UP: 'moveCursorUp',
    MOVE_CURSOR_DOWN: 'moveCursorDown',
    MOVE_CURSOR_TO_LINE_START: 'moveCursorToLineStart',
    MOVE_CURSOR_TO_LINE_END: 'moveCursorToLineEnd',
    MOVE_CURSOR_TO_TOP: 'moveCursorToTop',
    MOVE_CURSOR_TO_BOTTOM: 'moveCursorToBottom',
    SELECT_LEFT: 'selectLeft',
    SELECT_RIGHT: 'selectRight',
    SELECT_UP: 'selectUp',
    SELECT_DOWN: 'selectDown',
    SELECT_TO_LINE_START: 'selectToLineStart',
    SELECT_TO_LINE_END: 'selectToLineEnd',
    SELECT_TO_TOP: 'selectToTop',
    SELECT_TO_BOTTOM: 'selectToBottom',
    DESELECT_ALL: 'deselectAll',
    MOVE_LINE_UP: 'moveLineUp',
    MOVE_LINE_DOWN: 'moveLineDown',
    ADD_CURSOR_IN_PREVIOUS_LINE: 'moveLineUp',
    ADD_CURSOR_IN_NEXT_LINE: 'moveLineDown',
    RELOAD_FILE: 'reloadFile'
  };

}).call(this);

//# sourceMappingURL=events.js.map
