// Generated by CoffeeScript 1.11.1
(function() {
  var keyInfo, mods;

  mods = {
    Shift: '⇧',
    Control: '^',
    Alt: '⌥',
    Meta: '⌘',
    Dead: true
  };

  keyInfo = function(event) {
    var alt, char, cmd, code, ctrl, isChar, key, mod, shift;
    key = event.key;
    shift = event.shiftKey;
    ctrl = event.ctrlKey;
    alt = event.altKey;
    cmd = event.metaKey;
    isChar = key.length === 1 && !(ctrl || cmd);
    char = isChar ? key : '';
    code = event.code;
    code = key.length === 1 && /^Key/.test(code) ? code.slice(-1).toLowerCase() : code;
    mod = '';
    if (!mods[key] && !isChar) {
      if (shift) {
        mod += 'Shift+';
      }
      if (ctrl) {
        mod += 'Ctrl+';
      }
      if (alt) {
        mod += 'Alt+';
      }
      if (cmd) {
        mod += 'Cmd+';
      }
      mod += code;
    }
    return {
      isChar: isChar,
      char: char,
      isMod: mod.length > 0,
      mod: mod,
      key: key,
      code: code,
      shift: shift,
      ctrl: ctrl,
      alt: alt,
      cmd: cmd,
      event: event
    };
  };

  module.exports = keyInfo;

}).call(this);

//# sourceMappingURL=key-info.js.map
