// Generated by CoffeeScript 1.11.1
(function() {
  var DOM, Toolbar,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  DOM = require('../core/tree-one');

  Toolbar = (function(superClass) {
    extend(Toolbar, superClass);

    function Toolbar() {}

    Toolbar.prototype.render = function() {
      return {
        type: 'div',
        props: {
          className: 'toolbar',
          tabindex: 0,
          children: ['toolbar']
        }
      };
    };

    return Toolbar;

  })(DOM.Base);

  module.exports = Toolbar;

}).call(this);

//# sourceMappingURL=toolbar.js.map
