// Generated by CoffeeScript 1.12.5
(function() {
  var Cmd;

  Cmd = (function() {
    function Cmd() {}

    Cmd.prototype.execute = function() {
      return console.log('execute: ', this.event);
    };

    return Cmd;

  })();

  module.exports = Cmd;

}).call(this);

//# sourceMappingURL=replace-in-file.js.map
