// Generated by CoffeeScript 1.11.1
(function() {
  var Selection;

  Selection = (function() {
    function Selection(editor) {
      this.editor = editor;
      console.log('Selection.constructor');
      this.state = this.editor.state;
    }

    Selection.prototype.getSize = function() {
      return this.state.get('selections').size || 0;
    };

    Selection.prototype.getSelection = function(index) {
      var selection;
      if (index < 0 || index >= this.getSize()) {
        return null;
      }
      selection = this.state.getIn(['selections', index]).toJS();
      return cursor;
    };

    return Selection;

  })();

  module.exports = Selection;

}).call(this);

//# sourceMappingURL=selection.js.map
