// Generated by CoffeeScript 1.12.5
(function() {
  var Highlighter, Prism, t;

  t = Date.now();

  Prism = require('prismjs');

  require('prismjs/components/prism-coffeescript');

  console.log('prisom require: ', Date.now() - t);

  Highlighter = (function() {
    function Highlighter(editor) {
      this.editor = editor;
      console.log('Highlighter.constructor');
    }

    Highlighter.prototype.highlight = function(text) {
      return Prism.highlight(text, Prism.languages.coffeescript);
    };

    return Highlighter;

  })();

  module.exports = Highlighter;

}).call(this);

//# sourceMappingURL=highlighter.js.map
