// Generated by CoffeeScript 1.12.5
(function() {
  var Indexer;

  Indexer = (function() {
    function Indexer(editor) {
      this.editor = editor;
      console.log('Indexer.constructor');
    }

    return Indexer;

  })();

  module.exports = Indexer;

}).call(this);

//# sourceMappingURL=indexer.js.map
