// Generated by CoffeeScript 1.12.5
(function() {
  var Cursor;

  Cursor = (function() {
    function Cursor(renderer) {
      this.renderer = renderer;
      console.log('Cursor.constructor');
      this.height = this.renderer.letter.h + 4;
      this.view = document.createElement('span');
      this.view.className = 'cursor';
      this.view.style.height = this.height + 'px';
    }

    Cursor.prototype.update = function(data) {
      if (!this.data || this.data && this.data.col !== data.col) {
        this.x = data.col * this.renderer.letter.w;
        this.view.style.left = this.x + 'px';
      }
      if (!this.data || this.data && this.data.row !== data.row) {
        this.y = data.row * this.renderer.letter.h;
        this.view.style.top = this.y + 'px';
      }
      if (this.height !== this.renderer.letter.h) {
        this.height = this.renderer.letter.h + 4;
        this.view.style.height = this.height + 'px';
      }
      this.used = true;
      this.data = data;
      return this;
    };

    return Cursor;

  })();

  module.exports = Cursor;

}).call(this);

//# sourceMappingURL=cursor.js.map
