// Generated by CoffeeScript 1.12.5
(function() {
  var Meta;

  Meta = (function() {
    function Meta(editor) {
      this.editor = editor;
      console.log('Meta.constructor');
    }

    return Meta;

  })();

  module.exports = Meta;

}).call(this);

//# sourceMappingURL=meta.js.map
