// Generated by CoffeeScript 1.12.5
(function() {
  var Minimap;

  Minimap = (function() {
    function Minimap(editor) {
      this.editor = editor;
      console.log('Minimap.constructor');
      this.view = document.createElement('div');
      this.view.className = 'minimap';
    }

    return Minimap;

  })();

  module.exports = Minimap;

}).call(this);

//# sourceMappingURL=minimap.js.map
