// Generated by CoffeeScript 1.11.1
(function() {
  var Completion;

  Completion = (function() {
    function Completion(editor) {
      this.editor = editor;
      console.log('Completion.constructor');
    }

    return Completion;

  })();

  module.exports = Completion;

}).call(this);

//# sourceMappingURL=completion.js.map
