// Generated by CoffeeScript 1.11.1
(function() {
  var Cmd;

  Cmd = (function() {
    function Cmd() {}

    Cmd.prototype.execute = function(text) {
      return console.log('insertText: ', text);
    };

    return Cmd;

  })();

  module.exports = Cmd;

}).call(this);

//# sourceMappingURL=insert-text.js.map
